// Path: tools/training_observer.js
// Purpose: Render training evidence and request bounded spectator views of active labs.
const $=id=>document.getElementById(id);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=(v,d=1)=>Number(v||0).toFixed(d);const pct=v=>`${num(Number(v||0)*100,1)}%`;const rate=v=>`${num(Number(v||0)*60,2)}/s`;const age=v=>v==null?'—':v<60?`${Math.round(v)}s`:`${Math.round(v/60)}m`;
function pill(status){const bad=['failed','timed_out'].includes(status),wait=['queued','ready'].includes(status);return `<span class="pill ${bad?'bad':wait?'wait':''}">${esc(status||'unknown')}</span>`}
function table(headers,rows){if(!rows.length)return '<div class="empty">No evidence yet.</div>';return `<table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table>`}
function renderSummary(s){const q=s.statuses||{},d=[['Attempts',s.summary.episodes,`${q.queued||0} queued`],['Completed',q.completed||0,pct(s.summary.completion_rate)],['Generation',s.summary.generation,'immutable checkpoint'],['Mean reward',num(s.summary.mean_reward,3),'recent transitions'],['Live workers',s.active_workers,`${s.live_workers.length} known`]];$('summary').innerHTML=d.map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="detail">${x[2]}</div></div>`).join('')}
function viewButton(s,w){const ready=Boolean(s.view_control?.enabled&&s.view_control.worker_ids?.includes(w.worker_id)&&['ready','running'].includes(w.status)&&['provisioned','observed','executing','measuring'].includes(w.phase)&&w.episode_id&&w.surface);return `<button class="view-button" data-worker="${esc(w.worker_id)}" data-episode="${esc(w.episode_id)}" ${ready?'':'disabled'}>${ready?'View in Factorio':'View unavailable'}</button>`}
function setViewStatus(message,kind=''){const node=$('view-status');node.textContent=message;node.className=`view-status ${kind}`.trim()}
function setCleanupStatus(message,kind=''){const node=$('cleanup-status');node.textContent=message;node.className=`view-status ${kind}`.trim()}
function renderCleanupControl(s){const control=s.view_control||{},ids=control.worker_ids||[];if(!control.enabled||!ids.length){$('cleanup-control').innerHTML='';setCleanupStatus(control.reason||'Stale-surface cleanup is unavailable.');return}$('cleanup-control').innerHTML=`<label for="cleanup-worker">Training worker</label><select id="cleanup-worker">${ids.map(id=>`<option value="${esc(id)}">${esc(id)}</option>`).join('')}</select><button id="cleanup-stale" class="danger-button">Remove stale surfaces</button>`;document.querySelector('#cleanup-stale').addEventListener('click',e=>recycleStale(e.currentTarget))}
async function recycleStale(button){const worker=$('cleanup-worker').value;if(!window.confirm(`Remove unowned training surfaces on ${worker}? Active episodes are protected; connected-player surfaces are skipped.`))return;button.disabled=true;setCleanupStatus('Checking and removing stale training surfaces…','working');try{const response=await fetch('/api/recycle-stale',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:worker,confirmation:'RECYCLE_STALE_TRAINING_SURFACES'})});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);const removed=result.recycled||[];setCleanupStatus(removed.length?`Removed ${removed.length} stale surface(s): ${removed.join(', ')}`:'No removable stale surfaces found. Active or occupied surfaces were preserved.','success');await refresh()}catch(error){setCleanupStatus(`Stale-surface cleanup failed: ${error.message}`,'error');button.disabled=false}}async function focusView(button){button.disabled=true;setViewStatus('Moving the configured observer to the selected training lab…','working');try{const response=await fetch('/api/view',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({worker_id:button.dataset.worker,episode_id:button.dataset.episode})});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);setViewStatus(`Viewing ${result.surface} in Factorio as ${result.observer_name}.`,'success')}catch(error){setViewStatus(`View request failed: ${error.message}`,'error');button.disabled=false}}
function renderWorkers(s){const control=s.view_control||{};setViewStatus(control.enabled?'Ready to open the active training lab in Factorio.':(control.reason||'Training view control is unavailable.'));$('workers').innerHTML=table(['Worker / episode','Phase','Throughput','Sustain','Age','View'],s.live_workers.map(w=>`<tr><td><strong>${esc(w.worker_id)}</strong><br><span class="mono">${esc(w.episode_id)}</span><br><small>${esc(w.surface||'no active surface')}</small></td><td>${pill(w.status)}<br><small>${esc(w.phase)}</small></td><td>${rate(w.rate_per_tick)} / ${rate(w.target_rate_per_tick)}<div class="meter"><i style="width:${Math.min(100,w.rate_ratio*100)}%"></i></div></td><td>${pct(Math.min(1,w.sustain_ratio))}<div class="meter"><i style="width:${Math.min(100,w.sustain_ratio*100)}%"></i></div></td><td>${age(w.age_seconds)}${w.error?`<br><span class="pill bad">${esc(w.error)}</span>`:''}</td><td>${viewButton(s,w)}</td></tr>`));document.querySelectorAll('.view-button:not([disabled])').forEach(button=>button.addEventListener('click',()=>focusView(button)))}
function renderBottlenecks(s){const max=Math.max(1,...s.bottlenecks.map(b=>b.count));$('bottlenecks').innerHTML=s.bottlenecks.length?s.bottlenecks.map(b=>`<div class="bottleneck"><div class="bottleneck-head"><strong>${esc(b.kind)}</strong><span>${b.count}</span></div><div class="bar"><i style="width:${b.count/max*100}%"></i></div><small>${esc(b.example)}</small></div>`).join(''):'<div class="empty">No classified bottlenecks yet.</div>'}
function renderEpisodes(s){$('episodes').innerHTML=table(['Episode','Result','Action','Reward','Ticks'],s.recent_episodes.map(e=>`<tr><td><span class="mono">${esc(e.episode_id)}</span><br><small>${esc(e.worker_id)}</small></td><td>${pill(e.status)}<br><small>${esc(e.failure_kind)}</small></td><td class="mono">${esc(e.chosen_action_id)}</td><td>${num(e.reward_total,3)}</td><td>${e.elapsed_ticks}</td></tr>`))}
function renderResearch(s){const a=s.autoresearch_live||{};const live=a.phase?`<div class="note"><strong>Live: ${esc(a.phase)}</strong><br>${esc(a.model||a.reason||a.error||'local controller')}<br><small>${age(a.age_seconds)} ago &middot; ${esc(a.guidance_count??0)} guidance item(s)</small></div>`:'';const p=s.proposals.map(x=>{let body={};try{body=JSON.parse(x.proposal_json)}catch{}return `<div class="note"><strong>${esc(x.status)} &middot; ${esc(x.model)}</strong><br>${esc(body.hypothesis||'No hypothesis')}<br><small>${esc(x.created_utc)}</small></div>`}).join('');const m=table(['Model','Samples','Mean','Tokens','CPU MoE'],s.llm_runtime.map(x=>`<tr><td>${esc(x.model)}</td><td>${x.samples}</td><td>${num(x.mean_elapsed_ms,0)}ms</td><td>${num(x.mean_prompt_tokens,0)}/${num(x.mean_completion_tokens,0)}</td><td>${esc(x.n_cpu_moe??'--')}</td></tr>`));$('research').innerHTML=live+(p||'<div class="empty">No proposals yet.</div>')+m}function renderPolicies(s){$('policies').innerHTML=table(['Generation','Policy','Parent'],s.policies.map(p=>`<tr><td>${p.generation}</td><td class="mono">${esc(p.policy_id)}</td><td class="mono">${esc(p.parent_policy_id||'root')}</td></tr>`))}
function renderGuidance(s){$('guidance').innerHTML=s.guidance.length?s.guidance.map(g=>`<div class="note"><strong>${esc(g.focus)}</strong> ${g.active?'<span class="pill">active</span>':'<span class="pill wait">dismissed</span>'}<br>${esc(g.message)}<br><small>${esc(g.guidance_id)} · expires ${esc(g.expires_generation??'never')}</small></div>`).join(''):'<div class="empty">No human guidance. Use the nudge command when evidence suggests a direction.</div>'}
async function refresh(){try{const r=await fetch('/api/snapshot',{cache:'no-store'});if(!r.ok)throw new Error(`HTTP ${r.status}`);const s=await r.json();renderSummary(s);renderCleanupControl(s);renderWorkers(s);renderBottlenecks(s);renderEpisodes(s);renderResearch(s);renderPolicies(s);renderGuidance(s);$('updated').textContent=`Updated ${new Date(s.generated_utc).toLocaleTimeString()}`;document.body.className=s.database_error?'offline':'online';$('connection').textContent=s.database_error?`Database error: ${s.database_error}`:s.database_present?'Live evidence connected':'Waiting for training database'}catch(e){document.body.className='offline';$('connection').textContent=`Observer error: ${e.message}`}}refresh();setInterval(refresh,3000);
